// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLCN8fCIZ7trUjssvBkA9tq_UhvXBQpRI',
    appId: '1:874022105786:web:ae6ea45662b9eb284e4883',
    messagingSenderId: '874022105786',
    projectId: 'moreonlife-e380c',
    authDomain: 'moreonlife-e380c.firebaseapp.com',
    storageBucket: 'moreonlife-e380c.firebasestorage.app',
    measurementId: 'G-B3TXXSENLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0eqdaddLGBOzxWXXKjBDXdHjdAf9epF4',
    appId: '1:874022105786:android:c34505c3ad832d3c4e4883',
    messagingSenderId: '874022105786',
    projectId: 'moreonlife-e380c',
    storageBucket: 'moreonlife-e380c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA22Rd55pnHGXoyynAdSWfZu04sQNBlf8g',
    appId: '1:874022105786:ios:7fb79c5fddc889024e4883',
    messagingSenderId: '874022105786',
    projectId: 'moreonlife-e380c',
    storageBucket: 'moreonlife-e380c.firebasestorage.app',
    iosBundleId: 'com.example.moreonlife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA22Rd55pnHGXoyynAdSWfZu04sQNBlf8g',
    appId: '1:874022105786:ios:7fb79c5fddc889024e4883',
    messagingSenderId: '874022105786',
    projectId: 'moreonlife-e380c',
    storageBucket: 'moreonlife-e380c.firebasestorage.app',
    iosBundleId: 'com.example.moreonlife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLCN8fCIZ7trUjssvBkA9tq_UhvXBQpRI',
    appId: '1:874022105786:web:525a1a1384a9a9674e4883',
    messagingSenderId: '874022105786',
    projectId: 'moreonlife-e380c',
    authDomain: 'moreonlife-e380c.firebaseapp.com',
    storageBucket: 'moreonlife-e380c.firebasestorage.app',
    measurementId: 'G-2R3YZGF9L1',
  );
}
